[package]
name = "input-markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
process-trait = { path = "../process-trait" }
thiserror = "1.0"
async-trait = "0.1"
assay = "0.1"
pulldown-cmark = "0.9.2"
