[advisories]
ignore = [
	"RUSTSEC-2021-0079", # TODO: Upgrade to >=0.14.0 (hyper integer overflow)
]

[database]
path = ".cargo/advisory-db" # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true # Perform a `git fetch` before auditing (default: true)
stale = false # Allow stale advisory DB (i.e. no commits for 90 days, default: false)