[advisories]
ignore = [
	"RUSTSEC-2021-0078", # TODO: Upstream PR on tracing-honeycomb (hyper allow request smuggling using `Content-Length` header)
	"RUSTSEC-2021-0079", # TODO: Upgrade to >=0.14.0 (hyper integer overflow)
	"RUSTSEC-2020-0071", # TODO: Upstream PR on tracing-honeycomb (time potential segfault)
	"RUSTSEC-2021-0124", # TODO: Upstream PR on tracing-honeycomb (tokio data race in `oneshot` channel)
	"RUSTSEC-2020-0016", # TODO: Upstream PR on tracing-honeycomb (net2 unmaintained)
]

[database]
path = ".cargo/advisory-db" # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true # Perform a `git fetch` before auditing (default: true)
stale = false # Allow stale advisory DB (i.e. no commits for 90 days, default: false)