#cloud-config

# SOURCE: https://docs.openmediavault.org/en/latest/installation/on_debian.html

# Update package lists and upgrade installed packages
package_update: true
package_upgrade: true

bootcmd:
  - apt update
  - apt upgrade -y
  - apt install -y gnupg

# Install required packages
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - software-properties-common
  - lsb-release
  - postfix
  - cryptsetup
  - snapraid
  - mergerfs

# Configure APT sources for OpenMediaVault
apt:
  sources:
    openmediavault.list:
      keyid: D67506C878E08A94FD7E009424863F0C716B980B
      source: "deb [signed-by=$KEY_FILE] https://packages.openmediavault.org/public sandworm main"
      filename: openmediavault.list
    openmediavault-proposed.list:
      source: "deb [signed-by=/etc/apt/cloud-init.gpg.d/openmediavault.gpg] https://packages.openmediavault.org/public sandworm-proposed main"
      filename: openmediavault.list
    openmediavault-partner.list:
      source: "deb [signed-by=/etc/apt/cloud-init.gpg.d/openmediavault.gpg] https://packages.openmediavault.org/public sandworm partner"
      filename: openmediavault.list

# Create a default user with sudo privileges
users:
  - name: omvadmin
    gecos: OpenMediaVault Administrator
    sudo: ALL=(ALL) ALL
    groups: sudo, _ssh
    shell: /bin/bash
    lock_passwd: false
    # Password is 'omvadmin' - change this in production!
    plain_text_passwd: omvadmin

# Run commands once at first boot
runcmd:
  # Allow ssh access with password authentication
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

  # Install and setup OMV
  - |
    export LANG=C.UTF-8
    export DEBIAN_FRONTEND=noninteractive
    export APT_LISTCHANGES_FRONTEND=none

    apt-get update
    apt-get --yes --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages \
      --no-install-recommends --option DPkg::Options::="--force-confdef" \
      --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault

    # Populate the database.
    omv-confdbadm populate

    # Deploy host config
    omv-salt deploy run hosts

  # Install optional OMV extras (plugins)
  - >
    wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install |
    bash

  # Enable qemu-guest-agent
  - systemctl enable qemu-guest-agent

  # Update the initramfs to take the crypttab changes
  - update-initramfs -u

  # Create mountpoints
  - |
    mkdir -p /media/parity1
    mkdir -p /media/disk1
    mkdir -p /media/merged
    mkdir -p /var/snapraid

  # Disable cloud-init so it doesnt conflict with OMV on next boot
  - touch /etc/cloud/cloud-init.disabled

write_files:
  - path: /etc/crypttab
    owner: "root:root"
    permissions: "0644"
    content: |
      parity1 UUID=2580faaf-42b6-4a45-a97c-3b8482e6bcb6 /root/hdd_key luks,discard,tries=1
      disk1 UUID=dbb1e30c-44f3-4541-8941-2452a544b93b /root/hdd_key luks,discard,tries=1
  - path: /etc/fstab
    defer: true
    append: true
    content: |
      /dev/mapper/parity1 /media/parity1 xfs defaults,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5 0 2
      /dev/mapper/disk1 /media/disk1 xfs defaults,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5 0 2
      /media/disk* /media/merged mergerfs allow_other,use_ino,cache.files=auto-full,x-systemd.requires=/media/disk1,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5,x-systemd.automount,category.create=pfrd,func.getattr=newest,dropcacheonclose=true 0 0
  - path: /etc/snapraid.conf
    owner: "root:root"
    permissions: "0644"
    content: |
      parity /media/parity1/snapraid.parity

      content /var/snapraid/content
      content /media/disk1/snapraid.content

      disk d1 /media/disk1/
  - path: /etc/cron.d/snapraid
    owner: "root:root"
    content: |
      # Run snapraid sync daily at 05h00
      0 5 * * * root snapraid sync

# Configure power management settings
power_state:
  mode: reboot
  timeout: 30
  condition: true
