#cloud-config

# SOURCE: https://docs.openmediavault.org/en/latest/installation/on_debian.html

fqdn: nodes.reta.re
hostname: openmediavault

# Update package lists and upgrade installed packages
package_update: true
package_upgrade: true

timezone: Europe/Paris

bootcmd:
  - apt update
  - apt upgrade -y
  - apt install -y gnupg

# Install required packages
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - software-properties-common
  - lsb-release
  - postfix
  - cryptsetup
  - snapraid

# Configure APT sources for OpenMediaVault
apt:
  sources:
    openmediavault.list:
      keyid: D67506C878E08A94FD7E009424863F0C716B980B
      source: "deb [signed-by=$KEY_FILE] https://packages.openmediavault.org/public sandworm main"
      filename: openmediavault.list
    openmediavault-proposed.list:
      source: "deb [signed-by=/etc/apt/cloud-init.gpg.d/openmediavault.gpg] https://packages.openmediavault.org/public sandworm-proposed main"
      filename: openmediavault.list
    openmediavault-partner.list:
      source: "deb [signed-by=/etc/apt/cloud-init.gpg.d/openmediavault.gpg] https://packages.openmediavault.org/public sandworm partner"
      filename: openmediavault.list

# Create a default user with sudo privileges
users:
  - name: omvadmin
    gecos: OpenMediaVault Administrator
    sudo: ALL=(ALL) ALL
    groups: sudo, _ssh
    shell: /bin/bash
    lock_passwd: false
    # Password is 'omvadmin' - change this in production!
    plain_text_passwd: omvadmin

# Run commands once at first boot
runcmd:
  # Allow ssh access with password authentication
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

  # Install and setup OMV
  - |
    export LANG=C.UTF-8
    export DEBIAN_FRONTEND=noninteractive
    export APT_LISTCHANGES_FRONTEND=none

    apt-get update
    apt-get --yes --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages \
      --no-install-recommends --option DPkg::Options::="--force-confdef" \
      --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault

    # Populate the database.
    omv-confdbadm populate

    # Deploy host config
    omv-salt deploy run hosts

  # Install optional OMV extras (plugins)
  - >
    wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install |
    bash

  # Install mergerfs
  # https://forum.openmediavault.org/index.php?thread/47913-problems-installing-mergerfs/&pageNo=1
  - |
    omv-aptclean repos
    apt-get update
    apt-get --yes --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages \
      --no-install-recommends --option DPkg::Options::="--force-confdef" \
      --option DPkg::Options::="--force-confold" install mergerfs

  # Install dasel
  - |
    curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest \
      | grep browser_download_url \
      | grep linux_amd64 \
      | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
    mv ./dasel /usr/local/bin/dasel

  # Append manual disks to OMV config
  - cp /etc/openmediavault/config.xml /etc/openmediavault/config.xml.bak
  - |
    cat /etc/openmediavault/config.xml | \
    dasel put -r xml -t string -v "
      <comment>parity</comment>
      <dir>/media/parity1</dir>
      <freq>0</freq>
      <fsname>/dev/mapper/parity1</fsname>
      <hidden>0</hidden>
      <opts>defaults,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5</opts>
      <passno>2</passno>
      <type>xfs</type>
      <usagewarnthreshold>0</usagewarnthreshold>
      <uuid>04340e3b-3dd4-4d87-8b49-28beeace205d</uuid>
    " 'config.system.fstab.mntent.append()' | \
    dasel put -r xml -t string -v "
      <comment>data</comment>
      <dir>/media/disk1</dir>
      <freq>0</freq>
      <fsname>/dev/mapper/disk1</fsname>
      <hidden>0</hidden>
      <opts>defaults,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5</opts>
      <passno>2</passno>
      <type>xfs</type>
      <usagewarnthreshold>0</usagewarnthreshold>
      <uuid>4ab51432-fc50-4dc3-8f42-201db7fb052d</uuid>
    " 'config.system.fstab.mntent.append()' | \
    dasel put -r xml -t string -v "
      <comment>merged-data</comment>
      <dir>/media/merged</dir>
      <freq>0</freq>
      <fsname>e5f13730-4f09-4eb3-80f7-b2cfb3285e1d</fsname>
      <hidden>0</hidden>
      <opts>defaults,cache.files=auto-full,x-systemd.requires=/media/disk1,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5,x-systemd.automount,fsname=merged,category.create=pfrd,func.getattr=newest,dropcacheonclose=true</opts>
      <passno>0</passno>
      <type>fuse.mergerfs</type>
      <usagewarnthreshold>0</usagewarnthreshold>
      <uuid>fbd99896-28e0-4d0e-b3cf-e08f635fe2f9</uuid>
    " 'config.system.fstab.mntent.append()' \
    dasel put -r xml -t string -v "
      <pools>
        <pool>
          <uuid>e5f13730-4f09-4eb3-80f7-b2cfb3285e1d</uuid>
          <name>merged</name>
          <mntentref>fbd99896-28e0-4d0e-b3cf-e08f635fe2f9</mntentref>
          <paths>/media/disk1</paths>
          <createpolicy>epmfs</createpolicy>
          <minfreespace>10</minfreespace>
          <minfreespaceunit>G</minfreespaceunit>
          <options>defaults,cache.files=auto-full,x-systemd.requires=/media/disk1,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5,x-systemd.automount,category.create=pfrd,func.getattr=newest,dropcacheonclose=true</options>
        </pool>
      </pools>
    " 'merge(config.services)'
    dasel -r xml > /etc/openmediavault/config.xml

  - omv-salt deploy run fstab

  # Enable qemu-guest-agent
  - systemctl enable qemu-guest-agent

  # Update the initramfs to take the crypttab changes
  - update-initramfs -u

  # Create mountpoints
  - |
    mkdir -p /media/parity1
    mkdir -p /media/disk1
    mkdir -p /media/merged
    mkdir -p /var/snapraid

  # Disable cloud-init so it doesnt conflict with OMV on next boot
  - touch /etc/cloud/cloud-init.disabled

write_files:
  - path: /etc/crypttab
    owner: "root:root"
    permissions: "0644"
    content: |
      parity1 UUID=e5e2fa22-6b0d-4516-b5da-ffe826a02736 /root/hdd_key luks,discard,tries=1
      disk1 UUID=dbb1e30c-44f3-4541-8941-2452a544b93b /root/hdd_key luks,discard,tries=1
  # - path: /etc/fstab
  #   defer: true
  #   append: true
  #   content: |
  #     /dev/mapper/parity1 /media/parity1 xfs defaults,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5 0 2
  #     /dev/mapper/disk1 /media/disk1 xfs defaults,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5 0 2
  #     /media/disk* /media/merged mergerfs allow_other,use_ino,cache.files=auto-full,x-systemd.requires=/media/disk1,x-systemd.idle-timeout=15min,x-systemd.device-timeout=5,x-systemd.automount,category.create=pfrd,func.getattr=newest,dropcacheonclose=true 0 0
  - path: /etc/snapraid.conf
    owner: "root:root"
    permissions: "0644"
    content: |
      parity /media/parity1/snapraid.parity

      content /var/snapraid/content
      content /media/disk1/snapraid.content

      disk d1 /media/disk1/
  - path: /etc/cron.d/snapraid
    owner: "root:root"
    content: |
      # SYNC snapraid daily at 5:00
      0 5 * * * root snapraid sync
      # SCRUB snapraid weekly on monday at 4:00
      0 4 * * MON root snapraid scrub
  - path: /etc/collectd/collectd.conf.d/df.conf
    owner: "root:root"
    defer: true
    content: |
      <LoadPlugin df>
        Interval 1800
      </LoadPlugin>
      <Plugin df>
       	MountPoint "/"
       	FSType xfs
        FSType fuse.mergerfs
       	IgnoreSelected false
      </Plugin>

# Configure power management settings
power_state:
  mode: reboot
  timeout: 30
  condition: true
