apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 12h
  chart:
    spec:
      chart: longhorn
      version: "1.9.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
