apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - longhorn-nixos-path.yaml
  - kyverno-add-nixos-path-to-containers.yaml
  - kyverno-add-nixos-path-to-initcontainers.yaml
