apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 6h
  chart:
    spec:
      chart: app-template
      version: "4.0.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: common-charts
  values:
    controllers:
      pgadmin:
        replicas: 1
        containers:
          pgadmin:
            image: 
              repository: dpage/pgadmin4
              tag: 9.4.0
            env:
              PUID: 1000
              PGID: 1000
              TZ: Europe/Paris
              PGADMIN_DISABLE_POSTFIX: true
            envFrom:
              - secretRef:
                  name: pgadmin-secrets
            securityContext:
              runAsUser: 0
              runAsGroup: 0
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 100m
                memory: 512Mi

    service:
      pgadmin:
        controller: pgadmin
        type: ClusterIP
        ports:
          http:
            port: 80
            protocol: HTTP
      
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: false
        advancedMounts:
          pgadmin:
            pgadmin:
              - path: /var/lib/pgadmin
                readOnly: false
