apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: pgadmin
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:N+sTXiBnZGR6CPvcKG5kE7vQ0w==,iv:uX327CBwPUaekMFRw4t360ojTudUBxR+R64KxO68M38=,tag:o8PU6y8YW2KRjJ6eKW4lSA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:3jx0fMPjzjt5qYsGfukSGN7W2S1SJReVT2RDXzrJ0lD06BDpuGfhqIezGVvxw6xorg3iRm8Pptsf8it4M80s+g==,iv:rkV7weuxin7du5kjnqoypEyJm47vvKiIrpD76GA5JBQ=,tag:XqG0Gdf8hoFfnyPoSwEQ+g==,type:str]
sops:
    lastmodified: "2025-06-05T15:46:35Z"
    mac: ENC[AES256_GCM,data:tsiSHg5bn9fhMCo+CD7pZ6UjeS4OvCrjDwWS0usJ1ws9dTJ18ZXuPP7QuCp5qfMFWBruBaELbfNFJCNQi5Yz/zYGBMXD+xoMK0kWw1spA1qcUnHd+cZkDD9g/HkvlCXrfaqmP5fLgwq0s5+fqTWShdl5FD0NJZyLTI57NTYd63k=,iv:YCV+xxpe1lo3RKqPW5McnY8R+q9IvVn9LKcMD8SrvSA=,tag:T190zqHS0XiHc1mbK7im+A==,type:str]
    pgp:
        - created_at: "2025-06-05T15:18:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ZmICfIWU5oARAA0fO53xVvUIW3vtKwx4pFlsIMfy7ted3EDwlyjrXoAkn2
            sRGWrgYgpvqiUM6f1GoLFj6m9hE/A2FOvux9yMizJHEweKDzOtuPiaXFGJlWON+J
            KBD2EmJA4KltR4wUEHJ+Kpo0FVuPIDPmdyjiUOAPLEeDEu6Uugp1i36GrUzuC6q6
            wYSnyrse0yFgCVUtX9lUMTr+VpOlp6/q/T9i757vQapXUIQxZaFtu8EzJKa4EivC
            iFM81cQ1xUoLYgvkFdLzSr0pucFpBcaJySBE4KkthWmb2JJkNq1qRN7Fq3rJJOjL
            Xdy9tPwy3OXa1up1s9EmJJFfdUhS19Kikh3mZqC1f9WTJR5UTGkCDsmoPZ/ASpZn
            MiVC193UI1UYqYW6gM0Yrq2p9l+XopfytlhknuzDZ/zzm0KTX0qbZ7bgW10QaLHQ
            0n8djU8COn8w1jsksY7R6CrZQv9u8y+7wKPeLfwkBXEUq6yYyYYKF+C/h11Cp0ZE
            IRUZ/siAW71N5x9L2nwwAPOmqRtI8IPcfGew79Oe1hP1Bc6t1/UcDM3UMaB8bORr
            6JPPRTAxSwAfPHHNcCPFLwyPypRWA4JpBlMwaZoK8R8dnTr7QavXn6E/PwD2zEip
            MHw0Yx4QDxtTLn7shmTUij9rFEib71FIC+jSCxOkQxLEOiXmiDZ7abzwurGIFqDU
            aAEJAhCnEbMBnxvHmhzAE0Ef6dNbBR7/AN0uZk/szBYI4p2IxgtGuacuSNbURARC
            7RD6ZG3TFdgMq1EmgB/0IdishWVtcCzcWcLmVSirXhihA0zDjYEscoEYlZVDF3X0
            uG841tR2iFHL
            =nw3C
            -----END PGP MESSAGE-----
          fp: BF5ACB1786BD3BB9F4FABEEE275EF572DD0F3EB8
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
