boot sshport="8080":
  env NIX_SSHOPTS="-p {{sshport}}" nixos-rebuild boot \
    --target-host root@46.225.11.44 \
    -I nixos-config=./configuration.nix \
    -I nixpkgs=channel:nixos-25.11

deploy sshport="8080":
  env NIX_SSHOPTS="-p {{sshport}}" nixos-rebuild switch \
    --target-host root@46.225.11.44 \
    -I nixos-config=./configuration.nix \
    -I nixpkgs=channel:nixos-25.11
