media: media
content:
  - name: garden
    label: Garden
    type: collection
    path: 'room09-chaotic-library/content/garden'
    view:
      fields: [ title, draft, date, updated ]
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: updated
        label: Updated
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: taxonomies
        label: Taxonomies
        type: object
        fields:
          - name: tags
            label: Tags
            type: string
            list: true
      - name: extra
        label: Extra
        type: object
        fields:
          - name: serie
            label: Serie
            type: string
          - name: guid
            label: GUID
            type: uuid
            required: true
          - name: comments
            label: Comments
            type: object
            fields:
              - name: host
                label: Host
                type: string
              - name: id
                label: Post id
                type: string
      - name: body
        label: Body
        type: rich-text
  - name: notes
    label: Notes
    type: collection
    path: 'room09-chaotic-library/content/notes'
    view:
      fields: [ title, draft, date, updated ]
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: updated
        label: Updated
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: taxonomies
        label: Taxonomies
        type: object
        fields:
          - name: tags
            label: Tags
            type: string
            list: true
      - name: extra
        label: Extra
        type: object
        fields:
          - name: guid
            label: GUID
            type: uuid
            required: true
          - name: comments
            label: Comments
            type: object
            fields:
              - name: host
                label: Host
                type: string
              - name: id
                label: Post id
                type: string
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Zola config
    path: 'room09-chaotic-library/config.toml'
    type: file
    format: code
    fields: [{ name: body, type: code, options: { language: toml } }]
