media: media
content:
  - name: blog
    label: Blog
    type: collection
    path: 'room09-chaotic-library/content/blog'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Zola config
    path: 'room09-chaotic-library/config.toml'
    type: file