http:
  middlewares:
    umami:
      plugin:
        umami-feeder:
          umamiHost: "https://umami.v3rm.in"
          umamiUsername: <username>
          umamiPassword: <password>
          umamiTeamId: <id>
          trackErrors: false
          trackAllResources: false
          websites:
            prometheus.serv4.reta.re: <id>
            pgadmin.serv4.reta.re: <id>
            podinfo.serv4.reta.re: <id>
            longhorn.serv4.reta.re: <id>
            garage-hot.serv4.reta.re: <id>
            grafana.serv4.reta.re: <id>
            git.planchon.dev: <id>

    ratelimit:
      rateLimit:
        average: 100
        burst: 200
        period: 1s

  routers:
    metrics:
      rule: "Host(`laonastes`) && ClientIP(`10.89.0.1/16`) && PathPrefix(`/metrics`)"
      service: prometheus@internal
      entryPoints:
        - web

    http:
      priority: 1
      rule: "PathRegexp(`.*`)"
      service: inner-traefik-http
      middlewares:
        - ratelimit
        - umami
      entryPoints:
        - web

    # Bypass anubis
    bypass-anubis-https:
      priority: 200
      rule: "Host(`cloud.reta.re`) || Host(`umami.v3rm.in`)"
      service: inner-traefik-https
      entryPoints:
        - websecure
    bypass-anubis-http:
      priority: 200
      rule: "Host(`cloud.reta.re`) || Host(`umami.v3rm.in`)"
      service: inner-traefik-http
      middlewares:
        - ratelimit
      entryPoints:
        - web

    http-challenges:
      priority: 100
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      service: inner-traefik-http
      middlewares:
        - ratelimit
      entryPoints:
        - web

    services-https:
      priority: 1
      rule: "PathRegexp(`.*`)"
      service: inner-traefik-https
      middlewares:
        - umami
      entryPoints:
        - anubiswebsecure

    # Anubis routers
    anubis-https:
      # Setting Anubis to the lowest priority, so it only takes the slack
      priority: 1
      rule: "PathRegexp(`.*`)"
      service: anubis-https
      middlewares:
        - ratelimit
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    anubis-https:
      loadBalancer:
        servers:
          - url: "http://anubis-https:8443"
    inner-traefik-https:
      loadBalancer:
        servers:
          - url: "https://gerbil:443"
    inner-traefik-http:
      loadBalancer:
        servers:
          - url: "http://gerbil:80"
