api:
  insecure: true
  dashboard: false

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

experimental:
  plugins:
    umami-feeder:
      moduleName: "github.com/astappiev/traefik-umami-feeder"
      version: v1.3.0

accessLog:
  filePath: "/logs/access.log"
  format: json
  fields:
    defaultMode: keep
    names:
      StartUTC: drop
    headers:
      defaultMode: keep

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    manualRouting: true

log:
  level: "INFO" # "DEBUG"
  format: "common"

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/letsencrypt/acme.json"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "5m"
    allowACMEByPass: true
    http3: {}
  anubiswebsecure:
    address: ":3443"

serversTransport:
  insecureSkipVerify: true
