api:
  insecure: true
  dashboard: false

providers:
  file:
    filename: "/etc/traefik/dynamic_config.yml"

experimental:
  localPlugins:
    umami-feeder:
      moduleName: "github.com/astappiev/traefik-umami-feeder"

# accessLog:
#   format: json
#   fields:
#     defaultMode: keep
#     headers:
#       defaultMode: keep

log:
  level: "INFO" # "DEBUG"
  format: "common"

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/letsencrypt/acme.json"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "5m"
    allowACMEByPass: true
    http3: {}
  anubisweb:
    address: ":3080"
  anubiswebsecure:
    address: ":3443"

serversTransport:
  insecureSkipVerify: true
