#cloud-config

# SOURCE: https://pbs.proxmox.com/docs/installation.html#install-proxmox-backup-server-on-debian

fqdn: nodes.reta.re
hostname: proxmox-backup-server

# Update package lists and upgrade installed packages
package_update: true
package_upgrade: true

timezone: Europe/Paris

bootcmd:
  - apt update
  - apt upgrade -y
  - apt install -y gnupg

# Install required packages
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - software-properties-common
  - lsb-release
  - proxmox-backup-server
  - proxmox-backup
  - nfs-common

# Configure APT sources for OpenMediaVault
apt:
  sources:
    proxmox.list:
      keyid: F4E136C67CDCE41AE6DE6FC81140AF8F639E0C39
      source: "deb [signed-by=$KEY_FILE] http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription"
      filename: proxmox.list

# Change root user
users:
  - name: root
    lock_passwd: false
    # Password is 'root' - change this in production!
    plain_text_passwd: root

# Run commands once at first boot
runcmd:
  # Allow root ssh access
  - sed -i 's/#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
  # Allow ssh access with password authentication
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

  # Enable qemu-guest-agent
  - systemctl enable qemu-guest-agent

  # Create mountpoints
  - |
    mkdir /var/proxmox-backups

  # Disable cloud-init so it doesnt conflict with OMV on next boot
  - touch /etc/cloud/cloud-init.disabled

write_files:
  - path: /etc/fstab
    defer: true
    append: true
    content: |
      10.0.0.11:/proxmox-backup /var/proxmox-backups nfs defaults,nofail,intr,hard,rsize=8192,wsize=8192,timeo=14 0 0

# Configure power management settings
power_state:
  mode: reboot
  timeout: 30
  condition: true
