on:
  #push:
  #  branches: [main]
  #  paths:
  #    - 'room09-chaotic-library/**'
  workflow_dispatch:
    inputs:
      only-clearnet:
        description: 'Deploy only the clearnet version of the blog (to post on mastodon)'
        required: false
        type: boolean
        default: false
jobs:
  deploy:
    runs-on: docker
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            room09-chaotic-library
          fetch-depth: 1
      - name: Cache uncloud
        id: cache-uncloud
        uses: actions/cache@v5
        with:
          path: /usr/local/bin/uncloud
          key: ${{ runner.os }}-uncloud
      - name: Install uncloud
        if: steps.cache-uncloud.outputs.cache-hit != 'true'
        run: curl -fsS https://get.uncloud.run/install.sh | sh
      - name: Configure uncloud
        run: |
          cd room09-chaotic-library
          mkdir -p ~/.ssh
          echo "${{ secrets.UNCLOUD_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Deploy clearnet only
        if: inputs.only-clearnet == true
        run: |
          echo uncloud --connect "${{ secrets.UNCLOUD_CLUSTER }}" deploy -y personal-website
      - name: Deploy all
        if: inputs.only-clearnet != true
        run: |
          echo uncloud --connect "${{ secrets.UNCLOUD_CLUSTER }}" deploy -y
