[package]
name = "storage"
version = "0.1.0"
authors = ["v3rmine <v3rmine@astriiid.fr>"]
edition = "2018"

[dependencies]
slog = "2.7.0"
serde = { version = "1.0.124", features = ["derive"], default-features = false }
tar = "0.4.33"
thiserror = "1.0.24"
serde_json = "1.0.64"
