kubeconfig := absolute_path("../../.secrets/k3s/k3s.yaml")

alias k := kubectl
[no-cd]
kubectl *PARAMS:
  kubectl --kubeconfig {{kubeconfig}} {{PARAMS}}

alias h := helm
[no-cd]
helm *PARAMS:
  helm --kubeconfig {{kubeconfig}} {{PARAMS}}

flux-status:
  kubectl get fluxreport/flux -n flux-system -o yaml
