#cloud-config

# SOURCE: https://docs.openmediavault.org/en/latest/installation/on_debian.html

# Set system hostname
fqdn: openmediavault.nodes.reta.re

# Update package lists and upgrade installed packages
package_update: true
package_upgrade: true

# Install required packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - sudo
  - software-properties-common
  - lsb-release
  - postfix
  - openmediavault

# Configure APT sources for OpenMediaVault
apt:
  sources:
    openmediavault:
      source: "deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://packages.openmediavault.org/public sandworm main"
      filename: openmediavault.list
    openmediavault-proposed:
      source: "deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://packages.openmediavault.org/public sandworm-proposed main"
      filename: openmediavault-proposed.list
    openmediavault-partner:
      source: "deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://packages.openmediavault.org/public sandworm partner"
      filename: openmediavault-partner.list

# Create a default user with sudo privileges
users:
  - name: omvadmin
    gecos: OpenMediaVault Administrator
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    # Password is 'omvadmin' - change this in production!
    passwd: $6$rounds=4096$Uai6Zv8TCco$gzKGXMb7mlZ7GdgPYCqvABQH3gBD4MpvEBsMeH7nSbjDh4e7VNWgSX84HOIpnO1Ooa7SuOgXEnX7jbpBzL6WB0

# Run commands once at first boot
runcmd:
  # Initialize the system
  - omv-confdbadm populate

  # Install optional OMV extras (plugins)
  - >
    wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install |
    bash

  # Set file permissions
  - chmod 770 /srv

  # Apply network configuration
  - omv-salt deploy run network

  # Apply all pending changes
  - omv-salt deploy run all

  # Restart web service to ensure WebUI is available
  - systemctl restart openmediavault-engined.service

# Final message shown to the console
final_message: >
  OpenMediaVault installation has completed.
  Access the web interface at:
  http://${v1.local_hostname}:80 or http://${v1.local_ipv4}:80

# Configure power management settings
power_state:
  mode: reboot
  timeout: 30
  condition: true
