[tool.poetry]
name = "yotta"
version = "0.20.1"
description = ""
authors = []
packages = [{include = "yotta"}]

[tool.poetry.dependencies]
python = ">=3.7,<3.9"
semantic_version = ">=2.3.1,<3"
requests = ">=2.4.3,<3"
certifi = ">=2016.2.28"
PyGithub = ">=1.25,<2"
colorama = ">=0.3,<0.4"
hgapi = ">=1.7,<2"
Jinja2 = ">=2.7.0,<3"
cryptography = ">=2.8,<3"
PyJWT = ">=1.0,<2.0"
pathlib2 = ">=2.0"
jsonschema = ">=2.4.0,<3.0"
argcomplete = ">=0.8.0,<2.0"
mbed_test_wrapper = ">=0.0.3,<2.0.0"
intelhex = ">=2.0,<3.0"
jsonpointer = ">=1.9,<2.0"
markupsafe = "<2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
yotta = "yotta:main"
yt = "yotta:main"
