services:
  dokuwiki:
    image: dokuwiki/dokuwiki:stable
    pull_policy: always
    user: 1001:1001
    restart: unless-stopped
    volumes:
      - dokuwiki-data:/storage
    x-ports:
      - dokuwiki.serv4.reta.re:8080/http
    x-machines:
      - phloeomys

volumes:
  dokuwiki-data:
