[package]
name = "mamba-burn"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.16", features = ["ndarray", "train", "wgpu"] }
bincode = "=2.0.0-rc.3"
bincode_derive = "=2.0.0-rc.3"
