[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "process", "macros"] }
color-eyre.workspace = true
