apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - secret.yaml
postBuild:
  substituteFrom:
    - kind: Secret
      name: tailscale-credentials
