apiVersion: v1
kind: Secret
metadata:
    name: tailscale-credentials
    namespace: tailscale-system
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:qRL+J1V5J7TmCR7ZFWS4Oo0=,iv:qcYRABgh60tJiiPsnqq7hd6mrn6MKjasrrWGzK6kLuY=,tag:yXi0FzjxUD+3yRAErOuKcA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:7eOod1yBRT4Tw/7kFYa76F2Lu8g9HTfQmE3TZqmJQD+vO6PloEcHJmyRlfglM7H+4dwqyuHdUMXvlFIotd85nA==,iv:+J4HJdJIzKxpmRt986p2ZYg7zCb0v7/0+0kUrysQwn8=,tag:Bm+a6SOy88OBbFQCahlU/w==,type:str]
sops:
    lastmodified: "2025-05-27T09:16:13Z"
    mac: ENC[AES256_GCM,data:AySBChcZ+gnfthsvLrZhEUO47HCGiQ+J66AOmoxeH3MqcHTchxknk14du+3jdu4K359BhT7Ke3OIL6tNh0Qp6Mq53lZiydb8dh67nBZ1ksDqaJYoruzfmw2G/PeMeRn8rK0PnlD8VrxOOKnCPMsyS6jLSiufNzrYw5BAm13VTNk=,iv:GRkrQOwrmYK5rfj4NxK+v8nNttiUhS9f3ap0WXy8nHc=,tag:1mdv3hrJ/pivh1Q+Eq3JHA==,type:str]
    pgp:
        - created_at: "2025-05-26T15:30:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ZmICfIWU5oAQ/7B5VqUnZgZriFHxHTQ6solLKaqLT5TG9wYEBesZ5RSfCC
            cdkS4r/HHq7+CJDHrHjgm7ixAdvqSSUsoc0+zxzwPrW+3rlOCr8rgh4sIFdO7LOH
            g9BO8gJJ7uZX68tKV1fkZbd6KfozAsMFEO1mNvUeIvtYEHci/SpZdVGN5+3Y8zQ9
            67+FN/fykdwiUKNF9GflTi5zAll6NeGZWYV9rKrEg5HAjwAfTu/zLE+l0TTxTDoG
            WUJxwv5zRuLbAaRe991xyu7psLVxWqf+j2cn2LDyB3qP9z/2EYBV8KDP7/Yg7Xs0
            32CqDVmzc+w2y+0xpjugTv1tYxVPVAt7L673miJSSkhlKfRmRPgU9vYpa48sxX6x
            seZvpFIb6z0cnhydnqnWo21IPJnk3jtlb3XOPp9faifJOOwoA4RwS9MHRxcRfbf6
            weFIxGFljyi5+1VCysGP3fUcloX+PJZg8i36xvJD3bxT3vzMLqDHie65xYa8kEso
            ac/e8AFhkoVoifr0rZK1m+umfZqX0SjyJzpC92C3caURqNTVeuKGDrWwk2q96fQo
            ozOJqay8kLiRt/XkRIWWR5zO4xUzTD5Wu+UOPCy0ZCjSaBP3Wj+2r4fDUgdwVwgk
            SUi65b7qp7LUnhTpxfhMejLardudbCmyiG2PdjMXV3FIPVh4oBq9R3N3y4Cwag3U
            aAEJAhCrc13MZ7vDz4g0LZzmA66e74oTlkdS0w+qfidpZ7QNrLzSEbPLk0/2HrCZ
            ckgjcqt/d5SuEOMPrfMFDFm1HDLLS8Pj2n+9pt3R5Xd3zv85D9Q6cMU/MDh7lMUP
            jlQmKkDXMrpj
            =g5dL
            -----END PGP MESSAGE-----
          fp: BF5ACB1786BD3BB9F4FABEEE275EF572DD0F3EB8
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
