[package]
name = "entities"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.8", default-features = false, features = ["sqlx-sqlite", "macros", "runtime-tokio-rustls"] }
serde = { version = "1", features = ["derive"] }
