[package]
name = "org-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "^7.1"
miette = { version = "^4.2", features = ["fancy"] }
thiserror = "^1.0"

[dev-dependencies]
assay = "^0.1"
