[package]
name = "hello-world-transformer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-transformer-utils.workspace = true
wit-log.workspace = true
wit-sys.workspace = true

[package.metadata.component]
package = "component:hello-world-transformer"

[package.metadata.component.target]
path = "../../wit/transformer.wit"

[package.metadata.component.dependencies]
