credentials_file := "../../../../.secrets/terraform/proxmox.tfvars"
kubeconfig := "../../../../.secrets/k3s/k3s.yaml"

init:
  tofu init

plan: init
  tofu plan -var-file={{credentials_file}}

apply:
  tofu apply -var-file={{credentials_file}}

show:
  tofu show -var-file={{credentials_file}}

destroy:
  tofu destroy -var-file={{credentials_file}}

deploy:
  nixos-rebuild switch --target-host root@10.0.0.13 -I nixos-config=./configuration.nix -I nixpkgs=channel:nixos-24.11

kubectl *PARAMS:
  kubectl --kubeconfig {{kubeconfig}} {{PARAMS}}

helm *PARAMS:
  helm --kubeconfig {{kubeconfig}} {{PARAMS}}
