apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 6h
  chart:
    spec:
      chart: loki
      version: "6.30.1"
      sourceRef:
        kind: HelmRepository
        name: loki
  valuesFrom:
    - kind: Secret
      name: loki-secrets
      valuesKey: ACCESS_KEY_ID
      targetPath: loki.storage.s3.accessKeyId
    - kind: Secret
      name: loki-secrets
      valuesKey: SECRET_ACCES_KEY
      targetPath: loki.storage.s3.secretAccessKey
  values:
    deploymentMode: SingleBinary
    
    loki:
      auth_enabled: false # Typically true for production, but false is easier for initial setup
      commonConfig:
        replication_factor: 1

      storage:
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler

        type: s3
        s3:
          endpoint: https://garage-hot.serv4.reta.re
          region: garage

    # --- Ruler configuration (if you plan to use Loki for alerting) ---
    ruler:
      enabled: false # Set to true if you are using Loki for recording rules/alerts

