apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 6h
  chart:
    spec:
      chart: loki
      version: "6.30.1"
      sourceRef:
        kind: HelmRepository
        name: loki
  valuesFrom:
    - kind: Secret
      name: loki-secrets
      valuesKey: ACCESS_KEY_ID
      targetPath: loki.storage.s3.accessKeyId
    - kind: Secret
      name: loki-secrets
      valuesKey: SECRET_ACCES_KEY
      targetPath: loki.storage.s3.secretAccessKey
  values:
    deploymentMode: SingleBinary
    
    loki:
      # Disable multi-tenant support
      auth_enabled: false
      commonConfig:
        replication_factor: 1

      schemaConfig:
        configs:
          - from: "2024-04-01"
            object_store: s3
            store: tsdb
            schema: v13
            index:
              prefix: index_
              period: 24h

      pattern_ingester:
        enabled: true

      limits_config:
        ingestion_rate_mb: 8
        ingestion_burst_size_mb: 16
        max_global_streams_per_user: 5000
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        retention_period: 168h # 7 days retention
        allow_structured_metadata: true
        volume_enabled: true
  
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: longhorn

      compactor:
        retention_enabled: true

      storage:
        bucketNames:
          chunks: loki-chunks
        type: s3
        s3:
          endpoint: https://garage-hot.serv4.reta.re
          region: garage
          s3ForcePathStyle: false
          insecure: false

    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 1024Mi

    chunksCache:
      allocatedMemory: 1024
      writebackSizeLimit: 256MB

    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    ruler:
      enabled: false # Set to true if you are using Loki for recording rules/alerts
      replicas: 0

