apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: loki
  namespace: loki
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - secrets.yaml
  - tailscale.yaml
