apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: loki
  tailscale.com/hostname: loki
spec:
  loadBalancerClass: tailscale
  type: LoadBalancer
  ports:
    - name: loki
      port: 3100
      targetPort: 3100
