apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: loki
  annotations:
    tailscale.com/hostname: loki
spec:
  selector:
    app: loki
  loadBalancerClass: tailscale
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
