apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 6h
  chartRef:
    kind: OCIRepository
    name: forgejo
  valuesFrom:
    - kind: Secret
      name: forgejo-secrets
      valuesKey: FORGEJO_ADMIN_EMAIL
      targetPath: gitea.admin.email
    - kind: Secret
      name: forgejo-secrets
      valuesKey: FORGEJO_ADMIN_PASSWORD
      targetPath: gitea.admin.password
    - kind: Secret
      name: forgejo-secrets
      valuesKey: FORGEJO_DB_PASSWORD
      targetPath: gitea.config.database.PASSWD
  values:
    gitea:
      admin:
        username: v3rmine
        passwordMode: keepUpdated

      config:
        APP_NAME: 'Forgejo: Beyond coding. We forge.'

        repository:
          ENABLE_PUSH_CREATE_USER: true

        service:
          DISABLE_REGISTRATION: false
          REGISTER_EMAIL_CONFIRM: false
          REGISTER_MANUAL_CONFIRM: true
          REQUIRE_SIGNIN_VIEW: false

        cors:
          ENABLED: true
          ALLOW_DOMAIN: https://git.planchon.dev

        ui:
          SHOW_USER_EMAIL: false

        server:
          DOMAIN: git.planchon.dev
          ROOT_URL: https://git.planchon.dev/
          LANDING_PAGE: explore

        database:
          DB_TYPE: postgres
          HOST: postgres.postgres
          NAME: forgejo
          USER: forgejo

        mailer:
          ENABLED: false
          PROTOCOL: smtps+starttls
          SMTP_ADDR: ''
          SMTP_PORT: 587
          USER: ''
          PASSWD: ''
          FROM: ''

    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi

    postgresql-ha:
      enabled: false
    postgresql:
      enabled: false

    redis-cluster:
      enabled: false
    redis:
      enabled: true
