apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 12h
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    semver: '12.5.1'
