apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: forgejo
  namespace: forgejo
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - secrets.yaml
