apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: forgejo
stringData:
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:f7RgAveQwBRzFYjgZSt9mF50pQ==,iv:nHncqMLeue4kqdCIh45q/WfFoj/fzuZ6GrkVw+kvPbY=,tag:7hyKFN8IG+s1PlmBQ2ao6w==,type:str]
    FORGEJO_ADMIN_PASSWORD: ENC[AES256_GCM,data:ebUusD6e1aYfhq/YERCPwuL5ZOhKuYBB,iv:in5qYo23vUoKGHU0SJx/QyN6lEvHKDe3SC1gbZWd+u0=,tag:vaiEEY3oQbStlkajKYTGyQ==,type:str]
    FORGEJO_ADMIN_SECRET: ENC[AES256_GCM,data:Z0nUSD43u5EepAE5wzsZZ0IpQA1Tr1HRKreMS6MwEbsf/v1u0CusHjfktL31koKm1qxPky3SJoPkh69G9Op09A==,iv:ATSHJ5IjPy848abl+pBLW1/vyGO0i+IroWsJp9AAAvs=,tag:kNjRUkCybZstgskXjhVDvg==,type:str]
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:Vo9lm3HNbRUUjVvDtuqIn3eaZ3Xcia1LqFxj8uIc0Nc=,iv:GjaYPN+eyYqZHPVW4yf8J7RIQNnbjLSDob2dWiIbGEc=,tag:RkdesAuO9F1SHoUTUA4pMw==,type:str]
sops:
    lastmodified: "2025-06-10T15:32:11Z"
    mac: ENC[AES256_GCM,data:jtuZmq2lRDLbevhy1fydEWlaXkOSm9dExhMi51xGi0FUIZfIEq+ktNJYEaXFlEcf+A1ngbkmw5mkX5K26rEmj9GiFVYKs8u//09B3PWw+kRvtoeRePiyDrl84fE5RQHAaHIS++Jg340G7SudIIAfofbWxZpvN4jxcmKpFqbnWLY=,iv:lE248jrOsWVdP9rsyhlXXtIkXum4T6Q0mr2TA5nTA9M=,tag:IvAWWoaPeQToKlX7uXV+ew==,type:str]
    pgp:
        - created_at: "2025-06-06T15:24:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ZmICfIWU5oAQ//R1Vi8aKlajnyCYSZtO+T5lbKaLuG8YfCEdH70+kcnTit
            dSPiGysXUmDrltHmTLCvFOXkZ5Z6M85zab8Ere19VViKcLVCo7udveak3noFn1bx
            R0DY31h75UrxFIlQD4NLLdHZtEiHtEnEmHNqG7GDheRC1sgha9OHW22vfFeuvbwH
            t9Jrg4orew7ogeIw1CcRopElzxi6ZB+y0HGwKMVlLgaTviFEZ90dE/OR7d19SgAn
            R0PPuLO7zXCejXjeuiInMlHAitjO515us6h0MNQV/M1SrqzjiCxZBDNvnGqY1tuY
            1m4mB96cy343okR82PIsO/4mL9/cEdM6d8Hp3GO9Dr3QZTk0gq6Xva+pRmL7tuoH
            lJZhEQKP4/Cy5J2N+J/dNphsmMExzO3xEkZPnTRj8WODNawrFAPDskv2dKtsbxSF
            3S6C8JdzUWDlHKJZfkCs1VDuHcO0TvBTCXil0Q6olOH47YhkonK1VIDJO3Jx38yS
            Qqfe+J9aubwAJ6t2dKBmLEvSngbUXlWgetiwI8G2Q1XJ3WzheJr8wJ/Da+9RL2oe
            CAmktwX829u1pEFGcFftJpdF+Ob9tUCPnlyfhMzKM4rOJb1oNubLOzH/l9WZ9AiI
            noLqGZfcI+lcFywXFhP34l8y7LAS5y7sOUVY2UdV3J0ID+C6aH88kHOZAk2oqozU
            aAEJAhCMwK087rXduPqQMMsSBoInbWZUPjN0VqkcY6/O5CpNjFb4aDJXwHhjkAml
            +aMAPx31tQDb66iAOzMHVfnKn8etaTT5Ris0AZ/dsE6nvGAYGazKMkftTnaKKsvF
            d/Myl0u+1JI7
            =di0R
            -----END PGP MESSAGE-----
          fp: BF5ACB1786BD3BB9F4FABEEE275EF572DD0F3EB8
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
