# Display this help screen
help:
    @just --list --list-submodules

mod disk "justfiles/disk.just"
mod packages "justfiles/packages.just"
mod filesystem "justfiles/filesystem.just"
mod users "justfiles/users.just"
mod chroot "justfiles/chroot.just"

# Setup whole LFS
setup-virtual:
    #!/usr/bin/env bash
    set -euo pipefail

    just disk::create-virtual-disk
    just disk::connect-virtual-disk
    just disk::format-disk
    just disk::mount-parts

    just packages::get-packages

    just users::create-lfs-group
    just users::create-lfs-users

    just filesystem::create-base-filesystem

    just packages::build-pass-1
    just packages::build-pass-2

    just filesystem::patch-ownership-for-chroot
    just filesystem::mount-filesystem-for-chroot

    just filesystem::create-chroot-filesystem
    just filesystem::create-chroot-essentials

    just packages::build-pass-3

    just filesystem::cleanup-chroot-after-build
    just filesystem::backup-temporary-filesystem

    just disk::unmount-parts
    just disk::disconnect-virtual-disk
