kubeconfig := "../../.secrets/k3s/k3s.yaml"

boot sshport="8080":
  env NIX_SSHOPTS="-p {{sshport}}" nixos-rebuild boot --target-host root@ssh.serv4.reta.re -I nixos-config=./configuration.nix -I nixpkgs=channel:nixos-25.11-small

deploy sshport="8080":
  env NIX_SSHOPTS="-p {{sshport}}" nixos-rebuild switch --target-host root@ssh.serv4.reta.re -I nixos-config=./configuration.nix -I nixpkgs=channel:nixos-25.11-small

kubectl *PARAMS:
  kubectl --kubeconfig {{kubeconfig}} {{PARAMS}}

helm *PARAMS:
  helm --kubeconfig {{kubeconfig}} {{PARAMS}}
