apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-system
spec:
  interval: 6h
  chart:
    spec:
      chart: csi-driver-nfs
      version: "v4.11.0"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    storageClass:
      create: true
      name: nfs-csi
