http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  routers:
    # HTTP to HTTPS redirect router
    main-app-router-redirect:
      rule: "Host(`cloud.reta.re`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    # Next.js router (handles everything except API and WebSocket paths)
    next-router:
      rule: "Host(`cloud.reta.re`) && !PathPrefix(`/api`) && !PathPrefix(`/ws`)"
      service: next-service
      entryPoints:
        - websecure

    # API router (handles /api paths)
    api-router:
      rule: "Host(`cloud.reta.re`) && PathPrefix(`/api`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # WebSocket router
    ws-router:
      rule: "Host(`cloud.reta.re`) && PathPrefix(`/ws`)"
      service: api-service
      entryPoints:
        - websecure

  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002" # Next.js server

    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000" # API/WebSocket server
