apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: netdata-system
spec:
  interval: 5m
  chart:
    spec:
      chart: netdata
      version: "2"
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: Create
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik
      spec:
        ingressClassName: traefik
