[package]
name = "trans-train"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-utils.workspace = true

serde.workspace = true
toml.workspace = true
clap.workspace = true
tokio.workspace = true
async-trait.workspace = true
wasmtime.workspace = true
semver.workspace = true
eyre.workspace = true
color-eyre.workspace = true
miette.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rand.workspace = true
