apiVersion: v1
kind: Secret
metadata:
    name: umami-secrets
    namespace: umami
stringData:
    APP_SECRET: ENC[AES256_GCM,data:HLxo/XkwplnfvHua7An1UzBC22Pc2dRb8Q8XR3jB3Kwqot/PdmKWdXEITtGOs0KfNRiHwV+qIpP11XmhIT/Ujw==,iv:vfOsf96MUc6az6vhGcXcejcMVsGvCRqiu+JroOyR/rw=,tag:t6TvwPLx0Z80c3rYaqGoBw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:EAhDZAT74/g/Y+/JpvtwXBmREDpAtLrA1NwLoh/vZLRGZYeLL1yp0QQO1OxgMrSaVs5QvJ8530T+MIEU5wvnSwKyH5jxh+W7v6VIywiUuUA=,iv:vfog3WPlEi8ryP941CmQIEp/GZodm8i52yi5S03U5ik=,tag:HPNSCSY12gZNQmhE9Zu4qw==,type:str]
sops:
    lastmodified: "2025-06-06T15:24:40Z"
    mac: ENC[AES256_GCM,data:wNGm2DokhED1WEK15OeUftl+I5vRQiqHRHu3BjDHtTIWHCs+8i+xR9Gv/XggrZsmpXf8HJiHsT3XiSKyvo78SUaFJFapb/sXGX0SQAP5vC1utC0ZV7T0wj35M9xB0fyPRNUt25wyYDxzEJJdk62SZ+wLLTQ++zwOkYSfQA+0hvI=,iv:+4wCMDpnZGaS7Q4l2ZT8uls1Sje6b7NcvCgW4JtX+KQ=,tag:BPBNebt2YHAAEqW6rGmO4w==,type:str]
    pgp:
        - created_at: "2025-06-06T15:24:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ZmICfIWU5oAQ//R1Vi8aKlajnyCYSZtO+T5lbKaLuG8YfCEdH70+kcnTit
            dSPiGysXUmDrltHmTLCvFOXkZ5Z6M85zab8Ere19VViKcLVCo7udveak3noFn1bx
            R0DY31h75UrxFIlQD4NLLdHZtEiHtEnEmHNqG7GDheRC1sgha9OHW22vfFeuvbwH
            t9Jrg4orew7ogeIw1CcRopElzxi6ZB+y0HGwKMVlLgaTviFEZ90dE/OR7d19SgAn
            R0PPuLO7zXCejXjeuiInMlHAitjO515us6h0MNQV/M1SrqzjiCxZBDNvnGqY1tuY
            1m4mB96cy343okR82PIsO/4mL9/cEdM6d8Hp3GO9Dr3QZTk0gq6Xva+pRmL7tuoH
            lJZhEQKP4/Cy5J2N+J/dNphsmMExzO3xEkZPnTRj8WODNawrFAPDskv2dKtsbxSF
            3S6C8JdzUWDlHKJZfkCs1VDuHcO0TvBTCXil0Q6olOH47YhkonK1VIDJO3Jx38yS
            Qqfe+J9aubwAJ6t2dKBmLEvSngbUXlWgetiwI8G2Q1XJ3WzheJr8wJ/Da+9RL2oe
            CAmktwX829u1pEFGcFftJpdF+Ob9tUCPnlyfhMzKM4rOJb1oNubLOzH/l9WZ9AiI
            noLqGZfcI+lcFywXFhP34l8y7LAS5y7sOUVY2UdV3J0ID+C6aH88kHOZAk2oqozU
            aAEJAhCMwK087rXduPqQMMsSBoInbWZUPjN0VqkcY6/O5CpNjFb4aDJXwHhjkAml
            +aMAPx31tQDb66iAOzMHVfnKn8etaTT5Ris0AZ/dsE6nvGAYGazKMkftTnaKKsvF
            d/Myl0u+1JI7
            =di0R
            -----END PGP MESSAGE-----
          fp: BF5ACB1786BD3BB9F4FABEEE275EF572DD0F3EB8
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
