[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eyre.workspace = true
color-eyre.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
duct.workspace = true