[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^3.1", features = ["derive"] }
tokio = { version = "^1.17", features = ["rt-multi-thread", "process"] }
