#!/usr/bin/env python3
from json import (load, loads, dumps)
from sys import (stdin, stderr, argv)
from subprocess import (run)

def _in(instream, _dest="."):
    payload = load(instream)
    _source = payload["source"]
    version = payload["version"]

    # Do nothing we cannot pull a deployement
    return {
        "version": version,
        "metadata": [],
    }

if __name__ == "__main__":
    print(dumps(_in(stdin, argv[1]), separators=[",", ":"]))
