apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 6h
  chart:
    spec:
      chart: app-template
      version: "4.0.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: common-charts
  values:
    controllers:
      postgres:
        replicas: 1
        containers:
          postgres:
            image: 
              repository: postgres
              tag: 17.5-alpine
            envFrom:
              - secretRef:
                name: postgres-secrets
            securityContext:
              runAsUser: 0
              runAsGroup: 0
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 200m
                memory: 1024Mi

    service:
      postgres:
        controller: postgres
        type: ClusterIP
        ports:
          db:
            port: 5432
            protocol: tcp
      
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 5Gi
        retain: true
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
                readOnly: false
