apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 6h
  chart:
    spec:
      chart: app-template
      version: "4.0.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: common-charts
  values:
    controllers:
      postgres:
        replicas: 1
        containers:
          postgres:
            image: 
              repository: postgres
              tag: 17.5-alpine
            envFrom:
              - secretRef:
                name: postgres-secrets
            securityContext:
              runAsUser: 0
              runAsGroup: 0

    service:
      postgres:
        controller: postgres
        type: ClusterIP
        ports:
          db:
            ports: 5432
      
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 5Gi
        retain: true
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
                readOnly: false
