[package]
name = "gitlab-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
log-utils = { path = "../../services/log-utils" }

# Fuse filesystem
fuser = "0.11"
# Patched Gitlab client to support paginated Variables (partially documented https://docs.gitlab.com/ee/api/project_level_variables.html)
gitlab = { path = "../../services/gitlab" } # "0.1504"
# Deserializing Gitlab objects
serde = { version = "1.0", features = ["derive"] }
# Cli builder
clap = { version = "4.0.8", features = ["derive", "env"] }
# Error handling
eyre = "0.6"
color-eyre = "0.6"
# Gracefull termination handler
ctrlc = { version = "3.0", features = ["termination"] }
# RwLock / Mutex without deadlocks
parking_lot = "0.12"
# Libc for raw errors codes
libc = "0.2"
# Helper to make code cleaner
if_chain = "1.0"
