apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-test-app
  template:
    metadata:
      labels:
        app: longhorn-test-app
    spec:
      containers:
      - name: busybox-writer
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - 'echo "Hello from Longhorn!" > /mnt/longhorn-volume/testfile.txt;
            echo "Contents of testfile.txt:";
            cat /mnt/longhorn-volume/testfile.txt;
            echo "Sleeping forever...";
            tail -f /dev/null'
        volumeMounts:
        - name: longhorn-storage
          mountPath: /mnt/longhorn-volume
      volumes:
      - name: longhorn-storage
        persistentVolumeClaim:
          claimName: longhorn-test-pvc
