credentials_file := "../../../../.secrets/terraform/proxmox.tfvars"

init:
  tofu init

plan: init
  tofu plan -var-file={{credentials_file}}

apply:
  tofu apply -var-file={{credentials_file}}

show:
  tofu show -var-file={{credentials_file}}

destroy:
  tofu destroy -var-file={{credentials_file}}

boot sshport="8080":
  env NIX_SSHOPTS="-p {{sshport}}" nixos-rebuild boot \
    --target-host root@10.0.0.14 \
    -I nixos-config=./configuration.nix \
    -I nixpkgs=channel:nixos-25.11

deploy sshport="8080":
  env NIX_SSHOPTS="-p {{sshport}}" nixos-rebuild switch \
    --target-host root@10.0.0.14 \
    -I nixos-config=./configuration.nix \
    -I nixpkgs=channel:nixos-25.11
