# Games
"https://en.wikipedia.org/wiki/V_Rising" = ["V Rising"]
"https://en.wikipedia.org/wiki/Stardew_Valley" = ["Stardew Valley", "Stardew"]
"https://en.wikipedia.org/wiki/Coral_Island_(video_game)" = ["Coral Island"]

# Consoles
"https://www.ayntec.com/products/ayn-thor" = ["AYN Thor"]
"https://store.steampowered.com/steamdeck" = ["Steam Deck"]

# Projects
"https://github.com/Producdevity/gamehub-lite" = ["GameHub", "GameHub Lite"]
"https://iocaine.madhouse-project.org/" = ["Iocaine"]

# Services
"https://kagi.com/" = ["Kagi"]
