# Games
"https://en.wikipedia.org/wiki/V_Rising" = ["V Rising"]
"https://en.wikipedia.org/wiki/Stardew_Valley" = ["Stardew Valley", "Stardew"]
"https://en.wikipedia.org/wiki/Coral_Island_(video_game)" = ["Coral Island"]
"https://en.wikipedia.org/wiki/The_Wandering_Village" = ["The Wandering Village"]

# Consoles
"https://www.ayntec.com/products/ayn-thor" = ["AYN Thor"]
"https://store.steampowered.com/steamdeck" = ["Steam Deck"]

# Projects
"https://github.com/Producdevity/gamehub-lite" = ["GameHub", "GameHub Lite"]
"https://iocaine.madhouse-project.org/" = ["Iocaine"]
"https://github.com/doomemacs/doomemacs" = ["Doom", "Doom Emacs"]
"https://keats.github.io/tera/docs/" = ["Tera"]
"https://github.com/getzola/zola" = ["Zola"]
"https://github.com/miniflux/v2" = ["Miniflux"]
"https://github.com/vectordotdev/vector" = ["Vector"]
"https://github.com/VictoriaMetrics/VictoriaLogs" = ["VictoriaLogs"]
"https://github.com/VictoriaMetrics/VictoriaMetrics" = ["VictoriaMetrics"]
"https://github.com/grafana/grafana" = ["Grafana"]
"https://github.com/crowdsecurity/crowdsec" = ["Crowdsec"]
"https://github.com/navidrome/navidrome" = ["Navidrome"]
"https://www.proxmox.com/en/" = ["Proxmox"]
"https://github.com/lxc/lxc" = ["LXC"]
"https://bhyve.org/" = ["Bhyve"]
"https://activitypub.rocks/" = ["ActivityPub"]

# Services
"https://kagi.com/" = ["Kagi"]
"https://tailscale.com/" = ["Tailscale"]

# Who
"https://zoriya.dev" = ["Zoriya", "Zoe"]
