apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 12h
  chart:
    spec:
      chart: kyverno
      version: "3.4.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
  releaseName: kyverno
  targetNamespace: kyverno-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    features:
      admissionReports:
        enabled: false
      aggregateReports:
        enabled: false
      policyReports:
        enabled: false
      validatingAdmissionPolicyReports:
        enabled: false
